# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DirectLivestock' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DirectLivestock
  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  pod 'yoga', path: "#{rn_path}/ReactCommon/yoga/yoga.podspec"
  pod 'React', path: rn_path, subspecs: [
    'Core',
    'CxxBridge',
    'DevSupport',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTGeolocation',
    'RCTImage',
    'RCTLinkingIOS',
    'RCTNetwork',
    'RCTSettings',
    'RCTText',
    'RCTVibration',
    'RCTWebSocket',
  ]

  # React Native third party dependencies podspecs
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"

  # react-native-maps dependencies
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path  # Use Google map
  pod 'GoogleMaps'  # Support Google map
  pod 'Google-Maps-iOS-Utils' # Support Google map

  # Firebase
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'
  
  # Mixpanel
  pod 'Mixpanel'

  # target 'DirectLivestock-tvOSTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

  pod 'react-native-mixpanel', :path => '../node_modules/react-native-mixpanel'

  pod 'react-native-image-picker', :path => '../node_modules/react-native-image-picker'

  # target 'DirectLivestockTests' do
  #   inherit! :search_paths
  #   # Pods for testing
  # end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if target.name == 'react-native-google-maps'
      target.build_configurations.each do |config|
        config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
      end
    end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
      target.remove_from_project
    end
  end
end

# target 'DirectLivestock-tvOS' do
#   # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#   # use_frameworks!

#   # Pods for DirectLivestock-tvOS

#   target 'DirectLivestock-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end

# end
